### PR TITLE
OpenCL dynamic runtime support added

### PR DESCRIPTION
**Pull request by dmitry-zakablukov**
This pr adds a feature `dynamic-runtime` to load the OpenCL library in the runtime and avoid linkage errors during compilation stage (`OpenCL.lib not found`).

I have checked that there is no compilation warnings with both runtimes and with default and full features sets. I also have checked that `opencl3` library can be compiled with my changes (there are only two warnings about unused `Result`).

Tests are passing using the command `cargo test --all-features -- --test-threads=1`.

### CODE REVIEW

**Comment by kenba** [comment]
@dmitry-zakablukov please can you change this PR to use the current develop branch?

**Comment by dmitry-zakablukov** [comment]
@kenba , okay, but it will take some time.

**Comment by dmitry-zakablukov** [comment]
@kenba , I have updated the pr, but I cannot check compilation with the current version of `opencl-sys`.

Can you please apply this patch to `opencl-sys`?
[static.patch](https://github.com/user-attachments/files/17904763/static.patch)

In this patch all extern system functions are under the `static` feature.

**Comment by kenba** [comment]
@dmitry-zakablukov I've applied your patch to the develop branch.

**Comment by dmitry-zakablukov** [comment]
@kenba , thanks. I have updated the pr, all tests and examples can be compiled without errors now.

**Comment by kenba** [comment]
Thanks @dmitry-zakablukov merged in now.

**Pull request merged**
